<!DOCTYPE HTML>
<html lang="pt-br">
	<head>
		<?php $this->setEncoding('ISO-8859-1')?>
		<?php echo $this->render('head.phtml')?>
	</head>
	
	<body>
		<div class="header-content">
			<div class="header">
			
			</div>
		</div>
		
		<div class="main-content">
			<div class="main">
				<?php echo $this->layout()->content; ?>
			</div>
		</div>
		
		<div class="footer-content">
			<div class="footer">
			
			</div>
		</div>
		
		<?php echo $this->render('head-scripts.phtml')?>
	</body>
	

</html>